import "package:poker/poker.dart";

//Map jhtest={'AA', KK, QQ, JJ, TT, 99, 88, AKs, 77, AQs, AKo, AJs, ATs, AQo, AJo, KQs, 66, A9s, ATo, KJs, A8s, KTs, KQo, A7s, A9o, KJo, QJs, 55, A8o, A6s, K9s, A5s, KTo, QTs, A7o, A4s, K8s, QJo, A3s, K9o, Q9s, A6o, K7s, A5o, JTs, QTo, A2s, 44, K6s, A4o, K8o, Q8s, K5s, J9s, A3o, Q9o, K7o, JTo, K4s, A2o, Q7s, K6o, T9s, J8s, K3s, Q8o, Q6s, 33, J9o, K5o, K2s, Q5s, T8s, J7s, K4o, Q7o, Q4s, J8o, T9o, K3o, Q6o, 98s, T7s, J6s, Q3s, 22, K2o, Q5o, J5s, T8o, Q2s, J7o, 97s, T6s, Q4o, J4s, 98o, T7o, 87s, Q3o, J6o, J3s, 96s, T5s, J5o, J2s, Q2o, 97o, 86s, T4s, T6o, J4o, 95s, 76s, T3s, 87o, J3o, 96o, 85s, T2s, T5o, J2o, 94s, 75s, 86o, T4o, 93s};

final rankPairsInStrongnessOrder = [
  const RankPair.ofsuit(high: Rank.ace, kicker: Rank.ace),
  const RankPair.ofsuit(high: Rank.king, kicker: Rank.king),
  const RankPair.ofsuit(high: Rank.queen, kicker: Rank.queen),
  const RankPair.ofsuit(high: Rank.jack, kicker: Rank.jack),
  const RankPair.ofsuit(high: Rank.ten, kicker: Rank.ten),
  const RankPair.ofsuit(high: Rank.nine, kicker: Rank.nine),
  const RankPair.ofsuit(high: Rank.eight, kicker: Rank.eight),
  RankPair.suited(high: Rank.ace, kicker: Rank.king),
  const RankPair.ofsuit(high: Rank.seven, kicker: Rank.seven),
  RankPair.suited(high: Rank.ace, kicker: Rank.queen),
  const RankPair.ofsuit(high: Rank.ace, kicker: Rank.king),
  RankPair.suited(high: Rank.ace, kicker: Rank.jack),
  RankPair.suited(high: Rank.ace, kicker: Rank.ten),
  const RankPair.ofsuit(high: Rank.ace, kicker: Rank.queen),
  const RankPair.ofsuit(high: Rank.ace, kicker: Rank.jack),
  RankPair.suited(high: Rank.king, kicker: Rank.queen),
  const RankPair.ofsuit(high: Rank.six, kicker: Rank.six),
  RankPair.suited(high: Rank.ace, kicker: Rank.nine),
  const RankPair.ofsuit(high: Rank.ace, kicker: Rank.ten),
  RankPair.suited(high: Rank.king, kicker: Rank.jack),
  RankPair.suited(high: Rank.ace, kicker: Rank.eight),
  RankPair.suited(high: Rank.king, kicker: Rank.ten),
  const RankPair.ofsuit(high: Rank.king, kicker: Rank.queen),
  RankPair.suited(high: Rank.ace, kicker: Rank.seven),
  const RankPair.ofsuit(high: Rank.ace, kicker: Rank.nine),
  const RankPair.ofsuit(high: Rank.king, kicker: Rank.jack),
  RankPair.suited(high: Rank.queen, kicker: Rank.jack),
  const RankPair.ofsuit(high: Rank.five, kicker: Rank.five),
  const RankPair.ofsuit(high: Rank.ace, kicker: Rank.eight),
  RankPair.suited(high: Rank.ace, kicker: Rank.six),
  RankPair.suited(high: Rank.king, kicker: Rank.nine),
  RankPair.suited(high: Rank.ace, kicker: Rank.five),
  const RankPair.ofsuit(high: Rank.king, kicker: Rank.ten),
  RankPair.suited(high: Rank.queen, kicker: Rank.ten),
  const RankPair.ofsuit(high: Rank.ace, kicker: Rank.seven),
  RankPair.suited(high: Rank.ace, kicker: Rank.four),
  RankPair.suited(high: Rank.king, kicker: Rank.eight),
  const RankPair.ofsuit(high: Rank.queen, kicker: Rank.jack),
  RankPair.suited(high: Rank.ace, kicker: Rank.trey),
  const RankPair.ofsuit(high: Rank.king, kicker: Rank.nine),
  RankPair.suited(high: Rank.queen, kicker: Rank.nine),
  const RankPair.ofsuit(high: Rank.ace, kicker: Rank.six),
  RankPair.suited(high: Rank.king, kicker: Rank.seven),
  const RankPair.ofsuit(high: Rank.ace, kicker: Rank.five),
  RankPair.suited(high: Rank.jack, kicker: Rank.ten),
  const RankPair.ofsuit(high: Rank.queen, kicker: Rank.ten),
  RankPair.suited(high: Rank.ace, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.four, kicker: Rank.four),
  RankPair.suited(high: Rank.king, kicker: Rank.six),
  const RankPair.ofsuit(high: Rank.ace, kicker: Rank.four),
  const RankPair.ofsuit(high: Rank.king, kicker: Rank.eight),
  RankPair.suited(high: Rank.queen, kicker: Rank.eight),
  RankPair.suited(high: Rank.king, kicker: Rank.five),
  RankPair.suited(high: Rank.jack, kicker: Rank.nine),
  const RankPair.ofsuit(high: Rank.ace, kicker: Rank.trey),
  const RankPair.ofsuit(high: Rank.queen, kicker: Rank.nine),
  const RankPair.ofsuit(high: Rank.king, kicker: Rank.seven),
  const RankPair.ofsuit(high: Rank.jack, kicker: Rank.ten),
  RankPair.suited(high: Rank.king, kicker: Rank.four),
  const RankPair.ofsuit(high: Rank.ace, kicker: Rank.deuce),
  RankPair.suited(high: Rank.queen, kicker: Rank.seven),
  const RankPair.ofsuit(high: Rank.king, kicker: Rank.six),
  RankPair.suited(high: Rank.ten, kicker: Rank.nine),
  RankPair.suited(high: Rank.jack, kicker: Rank.eight),
  RankPair.suited(high: Rank.king, kicker: Rank.trey),
  const RankPair.ofsuit(high: Rank.queen, kicker: Rank.eight),
  RankPair.suited(high: Rank.queen, kicker: Rank.six),
  const RankPair.ofsuit(high: Rank.trey, kicker: Rank.trey),
  const RankPair.ofsuit(high: Rank.jack, kicker: Rank.nine),
  const RankPair.ofsuit(high: Rank.king, kicker: Rank.five),
  RankPair.suited(high: Rank.king, kicker: Rank.deuce),
  RankPair.suited(high: Rank.queen, kicker: Rank.five),
  RankPair.suited(high: Rank.ten, kicker: Rank.eight),
  RankPair.suited(high: Rank.jack, kicker: Rank.seven),
  const RankPair.ofsuit(high: Rank.king, kicker: Rank.four),
  const RankPair.ofsuit(high: Rank.queen, kicker: Rank.seven),
  RankPair.suited(high: Rank.queen, kicker: Rank.four),
  const RankPair.ofsuit(high: Rank.jack, kicker: Rank.eight),
  const RankPair.ofsuit(high: Rank.ten, kicker: Rank.nine),
  const RankPair.ofsuit(high: Rank.king, kicker: Rank.trey),
  const RankPair.ofsuit(high: Rank.queen, kicker: Rank.six),
  RankPair.suited(high: Rank.nine, kicker: Rank.eight),
  RankPair.suited(high: Rank.ten, kicker: Rank.seven),
  RankPair.suited(high: Rank.jack, kicker: Rank.six),
  RankPair.suited(high: Rank.queen, kicker: Rank.trey),
  const RankPair.ofsuit(high: Rank.deuce, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.king, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.queen, kicker: Rank.five),
  RankPair.suited(high: Rank.jack, kicker: Rank.five),
  const RankPair.ofsuit(high: Rank.ten, kicker: Rank.eight),
  RankPair.suited(high: Rank.queen, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.jack, kicker: Rank.seven),
  RankPair.suited(high: Rank.nine, kicker: Rank.seven),
  RankPair.suited(high: Rank.ten, kicker: Rank.six),
  const RankPair.ofsuit(high: Rank.queen, kicker: Rank.four),
  RankPair.suited(high: Rank.jack, kicker: Rank.four),
  const RankPair.ofsuit(high: Rank.nine, kicker: Rank.eight),
  const RankPair.ofsuit(high: Rank.ten, kicker: Rank.seven),
  RankPair.suited(high: Rank.eight, kicker: Rank.seven),
  const RankPair.ofsuit(high: Rank.queen, kicker: Rank.trey),
  const RankPair.ofsuit(high: Rank.jack, kicker: Rank.six),
  RankPair.suited(high: Rank.jack, kicker: Rank.trey),
  RankPair.suited(high: Rank.nine, kicker: Rank.six),
  RankPair.suited(high: Rank.ten, kicker: Rank.five),
  const RankPair.ofsuit(high: Rank.jack, kicker: Rank.five),
  RankPair.suited(high: Rank.jack, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.queen, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.nine, kicker: Rank.seven),
  RankPair.suited(high: Rank.eight, kicker: Rank.six),
  RankPair.suited(high: Rank.ten, kicker: Rank.four),
  const RankPair.ofsuit(high: Rank.ten, kicker: Rank.six),
  const RankPair.ofsuit(high: Rank.jack, kicker: Rank.four),
  RankPair.suited(high: Rank.nine, kicker: Rank.five),
  RankPair.suited(high: Rank.seven, kicker: Rank.six),
  RankPair.suited(high: Rank.ten, kicker: Rank.trey),
  const RankPair.ofsuit(high: Rank.eight, kicker: Rank.seven),
  const RankPair.ofsuit(high: Rank.jack, kicker: Rank.trey),
  const RankPair.ofsuit(high: Rank.nine, kicker: Rank.six),
  RankPair.suited(high: Rank.eight, kicker: Rank.five),
  RankPair.suited(high: Rank.ten, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.ten, kicker: Rank.five),
  const RankPair.ofsuit(high: Rank.jack, kicker: Rank.deuce),
  RankPair.suited(high: Rank.nine, kicker: Rank.four),
  RankPair.suited(high: Rank.seven, kicker: Rank.five),
  const RankPair.ofsuit(high: Rank.eight, kicker: Rank.six),
  const RankPair.ofsuit(high: Rank.ten, kicker: Rank.four),
  RankPair.suited(high: Rank.nine, kicker: Rank.trey),
  RankPair.suited(high: Rank.six, kicker: Rank.five),
  const RankPair.ofsuit(high: Rank.nine, kicker: Rank.five),
  RankPair.suited(high: Rank.eight, kicker: Rank.four),
  const RankPair.ofsuit(high: Rank.seven, kicker: Rank.six),
  const RankPair.ofsuit(high: Rank.ten, kicker: Rank.trey),
  RankPair.suited(high: Rank.nine, kicker: Rank.deuce),
  RankPair.suited(high: Rank.seven, kicker: Rank.four),
  const RankPair.ofsuit(high: Rank.eight, kicker: Rank.five),
  const RankPair.ofsuit(high: Rank.ten, kicker: Rank.deuce),
  RankPair.suited(high: Rank.six, kicker: Rank.four),
  RankPair.suited(high: Rank.five, kicker: Rank.four),
  RankPair.suited(high: Rank.eight, kicker: Rank.trey),
  const RankPair.ofsuit(high: Rank.seven, kicker: Rank.five),
  const RankPair.ofsuit(high: Rank.nine, kicker: Rank.four),
  RankPair.suited(high: Rank.eight, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.six, kicker: Rank.five),
  RankPair.suited(high: Rank.seven, kicker: Rank.trey),
  const RankPair.ofsuit(high: Rank.nine, kicker: Rank.trey),
  const RankPair.ofsuit(high: Rank.eight, kicker: Rank.four),
  RankPair.suited(high: Rank.six, kicker: Rank.trey),
  RankPair.suited(high: Rank.five, kicker: Rank.trey),
  const RankPair.ofsuit(high: Rank.nine, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.seven, kicker: Rank.four),
  RankPair.suited(high: Rank.seven, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.six, kicker: Rank.four),
  RankPair.suited(high: Rank.four, kicker: Rank.trey),
  const RankPair.ofsuit(high: Rank.five, kicker: Rank.four),
  const RankPair.ofsuit(high: Rank.eight, kicker: Rank.trey),
  RankPair.suited(high: Rank.six, kicker: Rank.deuce),
  RankPair.suited(high: Rank.five, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.eight, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.seven, kicker: Rank.trey),
  RankPair.suited(high: Rank.four, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.six, kicker: Rank.trey),
  const RankPair.ofsuit(high: Rank.five, kicker: Rank.trey),
  RankPair.suited(high: Rank.trey, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.seven, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.four, kicker: Rank.trey),
  const RankPair.ofsuit(high: Rank.six, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.five, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.four, kicker: Rank.deuce),
  const RankPair.ofsuit(high: Rank.trey, kicker: Rank.deuce),
];
